parameters:
    sonatra_security.acl.rule_extension.class: Sonatra\Bundle\SecurityBundle\Acl\DependencyInjection\RuleExtension
    sonatra_security.acl.rule_manager.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclRuleManager
    sonatra_security.acl.manipulator.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclManipulator
    sonatra_security.acl.manager.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclManager
    sonatra_security.acl.voter.class: Sonatra\Bundle\SecurityBundle\Core\Authorization\Voter\AclVoter

    # override standard object identity retriveal strategy
    security.acl.object_identity_retrieval_strategy.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityRetrievalStrategy

    # override acl provider
    security.acl.dbal.provider.class: Sonatra\Bundle\SecurityBundle\Acl\Dbal\MutableAclProvider

services:
    #Rule Extension
    sonatra_security.acl.rule_extension:
        class: '%sonatra_security.acl.rule_extension.class%'
        arguments: ['@service_container', ['@sonatra_security.acl.rule_definition']]
        public: false

    #Rule Manager
    sonatra_security.acl.rule_manager:
        class: '%sonatra_security.acl.rule_manager.class%'
        arguments:
            - '@sonatra_security.acl.rule_extension'
            - '%sonatra_security.acl_default_rule%'
            - '%sonatra_security.acl_rules%'

    #ACL Manipulator
    sonatra_security.acl.manipulator:
        class: '%sonatra_security.acl.manipulator.class%'
        arguments:
            - '@security.acl.provider'
            - '@security.acl.security_identity_retrieval_strategy'
            - '@security.acl.object_identity_retrieval_strategy'

    #ACL Manager
    sonatra_security.acl.manager:
        class: '%sonatra_security.acl.manager.class%'
        arguments:
            - '@security.acl.provider'
            - '@security.acl.security_identity_retrieval_strategy'
            - '@security.acl.object_identity_retrieval_strategy'
            - '@sonatra_security.acl.rule_manager'

    #Voter
    sonatra_security.acl.voter:
        public:    false
        class:     '%sonatra_security.acl.voter.class%'
        arguments:
            - '@sonatra_security.acl.manager'
            - '@security.acl.security_identity_retrieval_strategy'
        tags:      [ { name: security.voter, priority: 260 } ]

    #Acl Rule Definitions
    sonatra_security.acl.rule_definition.disabled:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\DisabledDefinition
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: disabled } ]

    sonatra_security.acl.rule_definition.allow:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\AllowDefinition
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: allow } ]

    sonatra_security.acl.rule_definition.deny:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\DenyDefinition
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: deny } ]

    sonatra_security.acl.rule_definition.affirmative:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\AffirmativeDefinition
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: affirmative } ]

    sonatra_security.acl.rule_definition.unanimous:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\UnanimousDefinition
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: unanimous } ]

    sonatra_security.acl.rule_definition.object:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\ObjectDefinition
        arguments: ['@sonatra_security.acl.manager', '@doctrine.orm.entity_manager']
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: object } ]

    sonatra_security.acl.rule_definition.class:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\ClassDefinition
        arguments: ['@sonatra_security.acl.manager', '@doctrine.orm.entity_manager']
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: class } ]
