parameters:
    sonatra_security.acl.rule_extension.class: Sonatra\Bundle\SecurityBundle\Acl\DependencyInjection\RuleExtension
    sonatra_security.acl.object_filter_extension.class: Sonatra\Bundle\SecurityBundle\Acl\DependencyInjection\ObjectFilterExtension
    sonatra_security.acl.rule_manager.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclRuleManager
    sonatra_security.acl.manipulator.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclManipulator
    sonatra_security.acl.manager.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclManager
    sonatra_security.acl.object_filter.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\AclObjectFilter
    sonatra_security.acl.voter.class: Sonatra\Bundle\SecurityBundle\Core\Authorization\Voter\AclVoter
    sonatra_security.acl.disable.listener.class: Sonatra\Bundle\SecurityBundle\Listener\DisableAclListener
    sonatra_security.acl_exception.base.class: Sonatra\Bundle\SecurityBundle\EventListener\AclExceptionListener

    # override standard object identity retriveal strategy
    security.acl.object_identity_retrieval_strategy.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\ObjectIdentityRetrievalStrategy

    # override acl provider
    security.acl.dbal.provider.class: Sonatra\Bundle\SecurityBundle\Acl\Dbal\MutableAclProvider

services:
    #Rule Extension
    sonatra_security.acl.rule_extension:
        class: '%sonatra_security.acl.rule_extension.class%'
        arguments: [['@sonatra_security.acl.rule_definition'], ['@sonatra_security.acl.rule_filter_definition']]
        properties:
            container: '@service_container'
        public: false

    #Object Filter Extension
    sonatra_security.acl.object_filter_extension:
        class: '%sonatra_security.acl.object_filter_extension.class%'
        arguments: [['@sonatra_security.acl.rule_definition']]
        properties:
            container: '@service_container'
        public: false

    #Rule Manager
    sonatra_security.acl.rule_manager:
        class: '%sonatra_security.acl.rule_manager.class%'
        arguments:
            - '@sonatra_security.acl.rule_extension'
            - '%sonatra_security.acl_default_rule%'
            - '%sonatra_security.acl_disabled_rule%'
            - '%sonatra_security.acl_rules%'

    #ACL Manipulator
    sonatra_security.acl.manipulator:
        class: '%sonatra_security.acl.manipulator.class%'
        arguments:
            - '@security.acl.provider'
            - '@security.acl.security_identity_retrieval_strategy'
            - '@security.acl.object_identity_retrieval_strategy'

    #ACL Manager
    sonatra_security.acl.manager:
        class: '%sonatra_security.acl.manager.class%'
        arguments:
            - '@security.acl.provider'
            - '@security.acl.security_identity_retrieval_strategy'
            - '@security.acl.object_identity_retrieval_strategy'
            - '@sonatra_security.acl.rule_manager'

    #ACL Object Filter
    sonatra_security.acl.object_filter:
        class: '%sonatra_security.acl.object_filter.class%'
        arguments:
            - '@sonatra_security.acl.object_filter_extension'
            - '@sonatra_security.acl.manager'
            - '@security.context'

    #Voter
    sonatra_security.acl.voter:
        public:    false
        class:     '%sonatra_security.acl.voter.class%'
        arguments:
            - '@sonatra_security.acl.manager'
            - '@security.acl.security_identity_retrieval_strategy'
        tags:      [ { name: security.voter, priority: 260 } ]

    #Disable ACL Listener
    sonatra_security.acl.disable.listener:
        class: '%sonatra_security.acl.disable.listener.class%'
        arguments: ['@sonatra_security.acl.manager']
        tags: [ { name: kernel.event_subscriber } ]

    sonatra_security.acl_exception.listener:
        class: '%sonatra_security.acl_exception.base.class%'
        tags: [{ name: kernel.event_listener, event: kernel.exception, method: onKernelException }]

    #Acl Object Filter Voter
    sonatra_security.acl.object_filter_voter.mixed:
        class: Sonatra\Bundle\SecurityBundle\Acl\ObjectFilter\MixedValue
        tags:   [ { name: sonatra_security.acl.object_filter_voter, priority: -255 } ]

    #Acl Rule Definitions
    sonatra_security.acl.rule_definition.disabled:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\Disabled
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: disabled } ]

    sonatra_security.acl.rule_definition.allow:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\Allow
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: allow } ]

    sonatra_security.acl.rule_definition.deny:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\Deny
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: deny } ]

    sonatra_security.acl.rule_definition.affirmative:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\Affirmative
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: affirmative } ]

    sonatra_security.acl.rule_definition.unanimous:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\Unanimous
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: unanimous } ]

    sonatra_security.acl.rule_definition.object:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\Object
        arguments: ['@sonatra_security.acl.manager']
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: object } ]

    sonatra_security.acl.rule_definition.class:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\ClassDefinition
        arguments: ['@sonatra_security.acl.manager']
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: class } ]

    sonatra_security.acl.rule_definition.parent:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\Definition\ParentDefinition
        arguments: ['@sonatra_security.acl.manager']
        tags:   [ { name: sonatra_security.acl.rule_definition, alias: parent } ]
