parameters:
    security.role_hierarchy.class: Sonatra\Bundle\SecurityBundle\Core\Role\RoleHierarchy

services:
    #Security Role Hierachy
    security.role_hierarchy:
        class:     '%security.role_hierarchy.class%'
        public:    false
        arguments: ['%security.role_hierarchy.roles%', '@doctrine', '%sonatra_security.role_class%']
