parameters:
    sonatra.security.role_hierarchy.base.class: Sonatra\Bundle\SecurityBundle\Core\Role\RoleHierarchy

services:
    #Security Role Hierachy
    sonatra.security.role_hierarchy:
        class:     '%sonatra.security.role_hierarchy.base.class%'
        arguments: ['@doctrine', '%sonatra_security.role_class%']
