parameters:
    sonatra_security.acl.orm.listener.class: Sonatra\Bundle\SecurityBundle\Doctrine\ORM\Listener\AclListener

services:
    sonatra_security.acl.orm.listener:
        public:    false
        class:     '%sonatra_security.acl.orm.listener.class%'
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, priority: 1 }
