parameters:
    sonatra_security.role.orm.listener.class: Sonatra\Bundle\SecurityBundle\Doctrine\ORM\Listener\RoleAuthorizationListener

services:
    #Doctrine Listener Role
    sonatra_security.role.orm.listener:
        public:    false
        class:     '%sonatra_security.role.orm.listener.class%'
        tags:
            - { name: doctrine.event_subscriber }
