parameters:
    sonatra.security.expression.has_field_permission_evaluator.class: Sonatra\Bundle\SecurityBundle\Acl\Expression\FieldPermissionEvaluator
    sonatra.security.expression.has_field_permission_compiler.class: Sonatra\Bundle\SecurityBundle\Acl\Expression\Compiler\Func\HasFieldPermissionFunctionCompiler

services:
    #JMS Expression
    sonatra.security.expression.has_field_permission_evaluator:
        public:    false
        class:     '%sonatra.security.expression.has_field_permission_evaluator.class%'
        arguments: ['@sonatra.acl.manager']

    sonatra.security.expression.has_field_permission_compiler:
        public: false
        class:  '%sonatra.security.expression.has_field_permission_compiler.class%'
        tags:
            - { name: security.expressions.function_compiler }
            - { name: security.expressions.variable, variable: field_permission_evaluator, service: sonatra.security.expression.has_field_permission_evaluator }
