parameters:
    sonatra_security.expression.has_permission.evaluator.class: Sonatra\Bundle\SecurityBundle\Acl\Expression\PermissionEvaluator
    sonatra_security.expression.has_permission.compiler.class: Sonatra\Bundle\SecurityBundle\Acl\Expression\Compiler\Func\HasPermissionFunctionCompiler

services:
    #JMS Expression
    sonatra_security.expression.has_permission.evaluator:
        public:    false
        class:     '%sonatra_security.expression.has_permission.evaluator.class%'
        arguments: ['@sonatra_security.acl.manager']

    sonatra_security.expression.has_permission.compiler:
        public: false
        class:  '%sonatra_security.expression.has_permission.compiler.class%'
        tags:
            - { name: security.expressions.function_compiler }
            - { name: security.expressions.variable, variable: permission_evaluator, service: sonatra_security.expression.has_permission.evaluator }
