parameters:
    # override standard security identity retriveal strategy
    security.acl.security_identity_retrieval_strategy.class: Sonatra\Bundle\SecurityBundle\Acl\Domain\SecurityIdentityRetrievalStrategy
    security.access.groupable_voter.class: Sonatra\Bundle\SecurityBundle\Core\Authorization\Voter\GroupableVoter

services:
    #Override security identity retriveal strategy service
    security.acl.security_identity_retrieval_strategy:
        class:  '%security.acl.security_identity_retrieval_strategy.class%'
        public: false
        arguments:
            - '@security.role_hierarchy'
            - '@security.authentication.trust_resolver'
        calls: [ ['setEventDispatcher', ['@?event_dispatcher']], ['setOrganizationalContext', ['@?sonatra_security.organizational_context']] ]

    security.access.groupable_voter:
        tags:  [ { name: security.voter, priority: 245 } ]
        class: '%security.access.groupable_voter.class%'
        public: false
        arguments:
            - '@security.acl.security_identity_retrieval_strategy'
