parameters:
    sonatra_security.host_role.authentication.provider.class: Sonatra\Bundle\SecurityBundle\Authentication\Provider\HostRoleProvider
    sonatra_security.host_role.authentication.listener.class: Sonatra\Bundle\SecurityBundle\Firewall\HostRoleListener

services:
    sonatra_security.host_role.authentication.provider:
        class: '%sonatra_security.host_role.authentication.provider.class%'
        arguments: []

    sonatra_security.host_role.authentication.listener:
        class: '%sonatra_security.host_role.authentication.listener.class%'
        arguments: ['@security.token_storage', [], '@security.authentication.listener.anonymous']
