parameters:
    sonatra_security.role_hierarchy.cache.listener.class: Sonatra\Bundle\SecurityBundle\Doctrine\ORM\Listener\RoleHierarchyListener

services:
    sonatra_security.role_hierarchy.cache.listener:
        class:     '%sonatra_security.role_hierarchy.cache.listener.class%'
        arguments: ['@sonatra_security.role_hierarchy.cache', '@security.acl.security_identity_retrieval_strategy', '@?sonatra_security.organizational_context']
        tags:
            - { name: doctrine.event_subscriber }
