parameters:
    sonatra_security.acl.dbal.options:
        class_table_name:         '%security.acl.dbal.class_table_name%'
        entry_table_name:         '%security.acl.dbal.entry_table_name%'
        oid_table_name:           '%security.acl.dbal.oid_table_name%'
        oid_ancestors_table_name: '%security.acl.dbal.oid_ancestors_table_name%'
        sid_table_name:           '%security.acl.dbal.sid_table_name%'

services:
    #Acl Rule Filter Definitions
    sonatra_security.acl.rule_filter_definition.orm.deny:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\FilterDefinition\OrmDeny
        tags:   [ { name: sonatra_security.acl.rule_filter_definition, alias: 'orm:deny' } ]

    sonatra_security.acl.rule_filter_definition.orm.affirmative:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\FilterDefinition\OrmAffirmative
        tags:   [ { name: sonatra_security.acl.rule_filter_definition, alias: 'orm:affirmative' } ]

    sonatra_security.acl.rule_filter_definition.orm.unanimous:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\FilterDefinition\OrmUnanimous
        tags:   [ { name: sonatra_security.acl.rule_filter_definition, alias: 'orm:unanimous' } ]

    sonatra_security.acl.rule_filter_definition.orm.object:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\FilterDefinition\OrmObject
        arguments: ['@doctrine.orm.entity_manager', '%sonatra_security.acl.dbal.options%']
        tags:   [ { name: sonatra_security.acl.rule_filter_definition, alias: 'orm:object' } ]

    sonatra_security.acl.rule_filter_definition.orm.class:
        class:  Sonatra\Bundle\SecurityBundle\Acl\Rule\FilterDefinition\OrmClass
        arguments: ['@doctrine.orm.entity_manager', '%sonatra_security.acl.dbal.options%']
        tags:   [ { name: sonatra_security.acl.rule_filter_definition, alias: 'orm:class' } ]
