parameters:
    sonatra_security.acl.orm.listener.class: Sonatra\Bundle\SecurityBundle\Doctrine\ORM\Listener\AclListener

services:
    sonatra_security.acl.orm.listener:
        public:    false
        class:     '%sonatra_security.acl.orm.listener.class%'
        arguments: ['@security.context', '@sonatra_security.acl.manager', '@sonatra_security.acl.rule_manager', '@sonatra_security.acl.object_filter']
        tags:
            - { name: doctrine.event_subscriber, priority: 1 }
