parameters:
    security.role_hierarchy.class: Sonatra\Bundle\SecurityBundle\Core\Role\RoleHierarchy
    sonatra_security.role_hierarchy.cache.class: Sonatra\Component\Cache\Adapter\PhpCache

services:
    #Override Security Role Hierachy
    security.role_hierarchy:
        class:     '%security.role_hierarchy.class%'
        public:    false
        arguments:
            - '%security.role_hierarchy.roles%'
            - '@doctrine'
            - '%sonatra_security.role_class%'
            - '@sonatra_security.role_hierarchy.cache'
        calls: [ ['setEventDispatcher', ['@?event_dispatcher']] ]

    sonatra_security.role_hierarchy.cache:
        class: '%sonatra_security.role_hierarchy.cache.class%'
        arguments: ['%sonatra_security.cache_dir%', 'role_hierarchy', '@filesystem']
